server:
    port : 8080

spring:
    datasource:
        url: jdbc:mariadb://mariadb:3306/CdO
        driverClassName: org.mariadb.jdbc.Driver
        username: root
        password: root
    jpa:
        database-platform: org.hibernate.dialect.MariaDBDialect
        hibernate:
            ddl-auto: update

logging:
    level:
        com.davidperezmillan.cdoinfoshowservice: INFO
        org.hibernate: WARN


