server:
    port : 8080

spring:
    datasource:
        url: jdbc:mariadb://192.168.1.195:3316/CdO
        driverClassName: org.mariadb.jdbc.Driver
        username: root
        password: root
    jpa:
        database-platform: org.hibernate.dialect.MariaDBDialect
        generate-ddl: true
        hibernate:
            ddl-auto: update

slack:
    bot:
        url: ${SLACK_URL}
        channel: series

scheduled:
    cron:
        expression: 0 0 */4 * * *
