server:
    port : 8080

spring:
    datasource:
        # url: jdbc:mariadb://mariadb:3306/CdO
        url: jdbc:mysql://localhost:3306/CdO
        driverClassName: org.mariadb.jdbc.Driver
        username: apps
        password: apps
    jpa:
        database-platform: org.hibernate.dialect.MariaDBDialect
        hibernate:
            ddl-auto: update

    test:
        classes: src/test/java

logging:
    level:
        com.davidperezmillan.cdoinfoshowservice: INFO
        org.hibernate: WARN


