spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/tu_basedatos
        driverClassName: org.mariadb.jdbc.Driver
        username: tu_usuario
        password: tu_contraseña
    jpa:
        database-platform: org.hibernate.dialect.MariaDBDialect
        hibernate:
            ddl-auto: update

logging:
    level:
        com.davidperezmillan.cdoinfoshowservice: INFO
        org.hibernate: WARN


