server:
    port : 8084

spring:
    datasource:
        url: jdbc:mariadb://192.168.1.195:3316/CdO
        driverClassName: org.mariadb.jdbc.Driver
        username: root
        password: root
    jpa:
        database-platform: org.hibernate.dialect.MariaDBDialect
        generate-ddl: true
        hibernate:
            ddl-auto: create-drop

    test:
        classes: src/test/java

logging:
    level:
        com.davidperezmillan.cdoinfoshowservice: DEBUG
        org.hibernate: DEBUG


