name: Multi-Service Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - CdInfoShowService
          - CdOVideoStoreService

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ matrix.service }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-${{ matrix.service }}-

    - name: List files
      run: ls -R

    - name: Build ${{ matrix.service }}
      working-directory: ${{ matrix.service }}
      run: mvn clean install

    - name: Copy JAR file to target directory
      run: |
        mkdir -p target
        cp target/*.jar target/app.jar

    - name: Commit JAR file
      uses: EndBug/add-and-commit@v9
      with:
        add: 'target/app.jar'
        message: 'Add JAR file to target directory'
        author_name: 'github-actions'
        author_email: 'github-actions@github.com'

    - name: Push changes
      run: git push
      env:
        GIT_AUTHOR_NAME: github-actions
        GIT_AUTHOR_EMAIL: github-actions@github.com
        GIT_COMMITTER_NAME: github-actions
        GIT_COMMITTER_EMAIL: github-actions@github.com
